### ISSUE TITLE
code dataset issues

### ISSUE THREAD

**Issue by happynewsday** [little1tow/DELE_pytorch#1]
We have installed the conda environment and SNLI dataset, but when executing your DELE model, the error message is as follows:
Traceback (most recent call last):
  File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/main.py", line 39, in <module>
    main()
  File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/main.py", line 27, in main
    solver = Solverv2(args)
  File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/solverV2.py", line 84, in __init__
    dataset = SNLIDataBertV2(args)
  File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/dataset.py", line 538, in __init__
    self._train_set = SNLIDataSet(self._args, split='train')
  File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/dataset.py", line 426, in __init__
    self.load_desp()
  File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/dataset.py", line 432, in load_desp
    with open(self.label_desp_path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/dataset/sentence_pair/snli/origin_file/snli_label_desp.txt'
Loading description data..../home/hlx/lishu/Tigaspace/3DELE_pytorch-main/dataset/sentence_pair/snli/origin_file/snli_label_desp.txt
#==================================================================
 
   
Where do snli_1.0_test_hard.txt and snli_label_desp.txt come from? Is it possible that the dataset we downloaded is incorrect, or have you performed additional data processing on SNLI? We hope you can provide an explanation and share the data processing code if applicable."

**Comment by laoba111** [comment]
Where do snli_1.0_test_hard.txt and snli_label_desp.txt come from? Is it possible that the dataset we downloaded is incorrect, or have you performed additional data processing on SNLI? We hope you can provide an explanation and share the data processing code if applicable."

**Comment by laoba111** [comment]
> We have installed the conda environment and SNLI dataset, but when executing your DELE model, the error message is as follows: Traceback (most recent call last): File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/main.py", line 39, in main() File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/main.py", line 27, in main solver = Solverv2(args) File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/solverV2.py", line 84, in **init** dataset = SNLIDataBertV2(args) File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/dataset.py", line 538, in **init** self._train_set = SNLIDataSet(self._args, split='train') File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/dataset.py", line 426, in **init** self.load_desp() File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/dataset.py", line 432, in load_desp with open(self.label_desp_path, 'r', encoding='utf-8') as f: FileNotFoundError: [Errno 2] No such file or directory: '/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/dataset/sentence_pair/snli/origin_file/snli_label_desp.txt' Loading description data..../home/hlx/lishu/Tigaspace/3DELE_pytorch-main/dataset/sentence_pair/snli/origin_file/snli_label_desp.txt #==================================================================
> 
> Where do snli_1.0_test_hard.txt and snli_label_desp.txt come from? Is it possible that the dataset we downloaded is incorrect, or have you performed additional data processing on SNLI? We hope you can provide an explanation and share the data processing code if applicable."

> We have installed the conda environment and SNLI dataset, but when executing your DELE model, the error message is as follows: Traceback (most recent call last): File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/main.py", line 39, in main() File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/main.py", line 27, in main solver = Solverv2(args) File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/solverV2.py", line 84, in **init** dataset = SNLIDataBertV2(args) File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/dataset.py", line 538, in **init** self._train_set = SNLIDataSet(self._args, split='train') File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/dataset.py", line 426, in **init** self.load_desp() File "/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/dataset.py", line 432, in load_desp with open(self.label_desp_path, 'r', encoding='utf-8') as f: FileNotFoundError: [Errno 2] No such file or directory: '/home/hlx/lishu/Tigaspace/3DELE_pytorch-main/dataset/sentence_pair/snli/origin_file/snli_label_desp.txt' Loading description data..../home/hlx/lishu/Tigaspace/3DELE_pytorch-main/dataset/sentence_pair/snli/origin_file/snli_label_desp.txt #==================================================================
> 
> Where do snli_1.0_test_hard.txt and snli_label_desp.txt come from? Is it possible that the dataset we downloaded is incorrect, or have you performed additional data processing on SNLI? We hope you can provide an explanation and share the data processing code if applicable."

are you fix it bro?

**Comment by Josoope** [comment]
I had the same problem. can't find snli_label_desp.txt

**Comment by Josoope** [comment]
> Where do snli_1.0_test_hard.txt and snli_label_desp.txt come from? Is it possible that the dataset we downloaded is incorrect, or have you performed additional data processing on SNLI? We hope you can provide an explanation and share the data processing code if applicable."

In the paper, it uses wordnet to descripe label. Maybe snli_label_desp.txt is generated by wordnet processing

**Comment by happynewsday** [comment]
I am not the author of this paper "Description-Enhanced Label Embedding Contrastive Learning for Text Classification", I just researched this code, but it didn't run successfully either, and emailed its real author, but didn't get a reply either, so I I gave up this research. So, I can't help you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月24日(星期三) 下午3:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [little1tow/DELE_pytorch] code dataset issues (Issue #1)














  
Where do snli_1.0_test_hard.txt and snli_label_desp.txt come from? Is it possible that the dataset we downloaded is incorrect, or have you performed additional data processing on SNLI? We hope you can provide an explanation and share the data processing code if applicable."
  
In the paper, it uses wordnet to descripe label. Maybe snli_label_desp.txt is generated by wordnet processing

**Comment by Josoope** [comment]
> I am not the author of this paper "Description-Enhanced Label Embedding Contrastive Learning for Text Classification", I just researched this code, but it didn't run successfully either, and emailed its real author, but didn't get a reply either, so I I gave up this research. So, I can't help you.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年4月24日(星期三) 下午3:56 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [little1tow/DELE_pytorch] code dataset issues (Issue #1) Where do snli_1.0_test_hard.txt and snli_label_desp.txt come from? Is it possible that the dataset we downloaded is incorrect, or have you performed additional data processing on SNLI? We hope you can provide an explanation and share the data processing code if applicable." In the paper, it uses wordnet to descripe label. Maybe snli_label_desp.txt is generated by wordnet processing — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

ok, thanks for your reply
